version: '2'

services:
    web:
        image: nginx
        ports:
            - "81:81"
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./src:/src
        networks:
            - code-network			
    db:
        image: postgres
        ports: 
            - "5432:5432"
        restart: always
        environment:
            #server: db
            #username: postgres
            POSTGRES_PASSWORD: example
            #database: postgres
        volumes:
            - ./src:/src
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - code-network
        #healthcheck:
        #    test: ["CMD", "curl", "-f", "http://localhost:5432"]
        #    test: ["CMD-SHELL", "pg_isready -U postgres"]
        #    interval: 15s
        #    timeout: 10s
        #    retries: 5
    adminer:
        image: adminer
        restart: always
        ports:
            - 5678:8080
        networks:
            - code-network


networks:
    code-network:
        driver: bridge